repos:
-   repo: git@github.com:Yelp/detect-secrets
    rev: v0.14.3
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline', '--custom-plugins', 'detect-secrets-plugins/']
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
